version: '3'

services:
  admin:
    build: ./admin_api
    container_name: admin_api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - admin_db
    # environment:
    #   - DATABASE_URL=postgres://admin_user:password@postgres:5432/admin_db


  admin_db:
    image: postgres:13
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


  frontend:
    build: ./frontend_api
    container_name: frontend_api
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - frontend_db
    # environment:
    #   - DATABASE_URL=mysql://frontend_user:password@mysql:3306/frontend_db


  frontend_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: frontend_db
      MYSQL_USER: frontend_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
