# Generated by Django 5.1.1 on 2024-09-19 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('borrow_days', models.IntegerField()),
                ('return_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.adminuser')),
            ],
        ),
    ]
